# Generated by Django 4.1 on 2025-11-10 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0003_alter_collection_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
