# Generated by Django 4.1 on 2025-11-10 11:59

import FinanceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_alter_collection_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_issued',
            field=models.DateField(default=FinanceApp.models.Loan.local_date),
        ),
    ]
