# Generated by Django 4.1 on 2025-11-10 12:18

import FinanceApp.models
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0006_alter_loan_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
