# Generated by Django 4.1 on 2025-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0007_alter_collection_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='loan_qrcodes/'),
        ),
    ]
