# Generated by Django 4.1 on 2025-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0008_loan_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.CharField(choices=[('in', 'Inflow'), ('out', 'Outflow')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(help_text='commission, collection, loan_disbursement, expense', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Loan code / Collection ID / Expense ID', max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Cash balance after this transaction', max_digits=12)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
