# Generated by Django 4.1 on 2025-12-24 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_cashledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Cash In'), ('out', 'Cash Out')], max_length=3)),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('collection', 'Loan Collection'), ('loan_disburse', 'Loan Disbursement'), ('expense', 'Expense'), ('dad_fund', 'Dad Fund'), ('dad_repay', 'Dad Repayment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceApp.loan')),
            ],
        ),
        migrations.DeleteModel(
            name='CashLedger',
        ),
    ]
