# Generated by Django 4.1 on 2025-12-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0010_cashtransaction_delete_cashledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='note',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='related_loan',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='txn_type',
            field=models.CharField(choices=[('capital', 'Capital In'), ('loan_disbursement', 'Loan Disbursement'), ('commission', 'Commission'), ('collection', 'Collection'), ('expense', 'Expense')], default='capital', max_length=30),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='direction',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=6),
        ),
    ]
