# Generated by Django 4.1 on 2025-12-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0013_loandisbursement_delete_loanextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandisbursement',
            name='collected_till_now',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
