# Generated by Django 4.1 on 2026-01-03 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0014_loandisbursement_collected_till_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='txn_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
