# Generated by Django 4.1 on 2026-01-04 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0015_cashtransaction_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandisbursement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
