# Generated by Django 4.1 on 2026-01-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0016_alter_loandisbursement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Bank')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='collection',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Bank')], default='cash', max_length=10),
        ),
    ]
