# Generated by Django 4.2.28 on 2026-06-27 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0017_cashtransaction_payment_mode_collection_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='[6-9]\\d{9}$')])),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='txn_type',
            field=models.CharField(choices=[('capital', 'Capital In'), ('capital_out', 'Capital Out'), ('loan_disbursement', 'Loan Disbursement'), ('commission', 'Commission'), ('collection', 'Collection'), ('expense', 'Expense')], default='capital', max_length=30),
        ),
    ]
