# Generated by Django 4.2.28 on 2026-06-28 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0018_fundsource_remove_loan_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundsource',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='fundsource',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundsource',
            name='date',
            field=models.DateField(default=datetime.date(2026, 6, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundsource',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
