# Generated by Django 4.2.28 on 2026-06-28 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0019_remove_fundsource_mobile_number_fundsource_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsource',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
    ]
