# Generated by Django 4.2.28 on 2026-06-29 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0020_alter_fundsource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsource',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
