# Generated by Django 4.2.28 on 2026-06-29 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0022_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsource',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Bank')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='txn_type',
            field=models.CharField(choices=[('capital', 'Capital In'), ('capital_out', 'Capital Out'), ('fund_source', 'Fund Source'), ('fund_repayment', 'Fund Repayment'), ('loan_disbursement', 'Loan Disbursement'), ('commission', 'Commission'), ('collection', 'Collection'), ('expense', 'Expense')], default='capital', max_length=30),
        ),
        migrations.AlterField(
            model_name='fundsource',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
