# Generated by Django 4.2.28 on 2026-06-29 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0023_fundsource_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Bank')], default='cash', max_length=10)),
                ('repayment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fund_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='FinanceApp.fundsource')),
            ],
        ),
    ]
