# Generated by Django 4.2.28 on 2026-06-29 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0024_fundrepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('borrow', 'Borrow'), ('repayment', 'Repayment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Bank')], default='cash', max_length=10)),
                ('txn_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fundsource',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fundsource',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fundsource',
            name='payment_mode',
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='txn_type',
            field=models.CharField(choices=[('capital', 'Capital In'), ('capital_out', 'Capital Out'), ('fund_source', 'Fund Borrowed'), ('fund_repayment', 'Fund Repaid'), ('loan_disbursement', 'Loan Disbursement'), ('commission', 'Commission'), ('collection', 'Collection'), ('expense', 'Expense')], default='capital', max_length=30),
        ),
        migrations.AlterField(
            model_name='fundsource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='FundRepayment',
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='fund_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='FinanceApp.fundsource'),
        ),
    ]
