# Generated by Django 4.2.28 on 2026-06-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0025_fundtransaction_remove_fundsource_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundtransaction',
            old_name='txn_date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='txn_type',
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('received', 'Money Received'), ('repayment', 'Money Repaid')], default='received', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='txn_type',
            field=models.CharField(choices=[('capital', 'Capital In'), ('capital_out', 'Capital Out'), ('fund_in', 'Fund Received'), ('fund_repayment', 'Fund Repaid'), ('loan_disbursement', 'Loan Disbursement'), ('commission', 'Commission'), ('collection', 'Collection'), ('expense', 'Expense')], default='capital', max_length=30),
        ),
    ]
