# Generated by Django 4.2.28 on 2026-07-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0026_rename_txn_date_fundtransaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='FinanceApp.collection'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='FinanceApp.expense'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='fund_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='FinanceApp.fundtransaction'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='loan_disbursement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='FinanceApp.loandisbursement'),
        ),
    ]
